version: 0.1

phases:
  build:
    commands:
      - |
        echo $CODEBUILD_SOURCE_VERSION
        export OBJECT_KEY=$(echo $CODEBUILD_SOURCE_VERSION | cut -d'/' -f2-)
        export BUCKET_NAME=$(echo $CODEBUILD_SOURCE_VERSION | cut -d'/' -f1)

        echo Build started on `date`
        dt=$(date +%F-%H%M%S)
        codeReviewArn=$(aws codeguru-reviewer create-code-review --repository-association-arn $CODEGURU_ASSOCIATION --type '{"RepositoryAnalysis":{"SourceCodeType":{"S3BucketRepository":{"Name":'\"${CODEGURU_REPO_NAME}\"',"Details":{"BucketName":'\"${BUCKET_NAME}\"',"CodeArtifacts":{"SourceCodeArtifactsObjectKey":"${OBJECT_KEY}"}}}}}}' --name flask-app-analysis-$dt | jq -r '.CodeReview.CodeReviewArn')
        echo "Waiting for code review results: $codeReviewArn..."
